runtime: custom
env: flex

service: default

env_variables:
  STREAMLIT_SERVER_PORT: "8080"  # Match the port in Dockerfile
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"

resources:
  cpu: 1
  memory_gb: 25
  disk_size_gb: 10

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2