runtime: custom
env: flex
image: gcr.io/premium-state-449406-n8/planet-demo:v1

service: default

env_variables:
  STREAMLIT_SERVER_PORT: "8080"  # Match the port in Dockerfile
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"

resources:
  cpu: 1
  memory_gb: 5
  disk_size_gb: 10

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2